server:
  port: 80
management:
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: gateway-service
    #zipkin: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: person-service
          uri: lb://person-service
          predicates:
            - Path=/api/v1/persona/**
        - id: vehiculo-service
          uri: lb://vehiculo-service
          predicates:
            - Path=/api/v1/vehiculo/**